# Generated by Django 2.0.2 on 2018-02-20 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('modify_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Datetime Modified')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_created_by', to=settings.AUTH_USER_MODEL)),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_modify_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ffba_product',
            },
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('modify_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Datetime Modified')),
                ('note', models.TextField(blank=True, null=True)),
                ('weight_initial', models.DecimalField(blank=True, decimal_places=5, max_digits=11, null=True)),
                ('composition', models.ForeignKey(db_column='composition_code', on_delete=django.db.models.deletion.PROTECT, related_name='composition', to='prod.Product', to_field='code')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productcomposition_created_by', to=settings.AUTH_USER_MODEL)),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productcomposition_modify_user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_code', on_delete=django.db.models.deletion.PROTECT, related_name='product', to='prod.Product', to_field='code')),
            ],
            options={
                'db_table': 'ffba_product_composition',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('modify_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Datetime Modified')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('show_order', models.CharField(blank=True, max_length=50, null=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producttype_created_by', to=settings.AUTH_USER_MODEL)),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producttype_modify_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ffba_product_type',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(db_column='product_type_code', on_delete=django.db.models.deletion.PROTECT, to='prod.ProductType', to_field='code'),
        ),
    ]
