# Generated by Django 2.0.3 on 2018-03-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomposition',
            name='up',
            field=models.ForeignKey(db_column='up_code', on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='prod.Product', to_field='code'),
        ),
    ]
