# Generated by Django 2.0.7 on 2018-07-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_auto_20180309_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='note',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='show_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
