# Generated by Django 2.1 on 2018-08-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0003_auto_20180719_1332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcomposition',
            unique_together={('up', 'product')},
        ),
    ]
