# Generated by Django 2.0.2 on 2018-02-20 11:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('modify_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Datetime Modified')),
                ('record_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('checks', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'ffba_cash_record',
                'ordering': ['record_date', 'cash_register'],
                'permissions': (('cash_record_create', 'cashrecord / create'), ('cash_record_create_any', 'cashrecord / createany'), ('cash_record_update', 'cashrecord / update'), ('cash_record_update_any', 'cashrecord / updateany'), ('cash_record_list', 'cashrecord / list'), ('cash_record_list_all', 'cashrecord / listall')),
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Created')),
                ('modify_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Datetime Modified')),
                ('name', models.CharField(max_length=200)),
                ('show_order', models.CharField(blank=True, max_length=100, null=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashregister_created_by', to=settings.AUTH_USER_MODEL)),
                ('modify_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashregister_modify_user', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='org.OrgUnit')),
            ],
            options={
                'db_table': 'ffba_cash_register',
                'ordering': ['show_order'],
            },
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_records', to='ae.CashRegister', unique_for_date='record_date'),
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashrecord_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='modify_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashrecord_modify_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cashregister',
            unique_together={('name', 'org_unit')},
        ),
    ]
