"""
FFBA django settings.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "1lv039s&v3-!a3b#*2&0^e%yi1yn6ar-7l!uz8x=jkuhmse+m#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 3-rd party apps
    # "webpack_loader", # TODO: delete - seems it is not needed
    "widget_tweaks",
    "debug_toolbar",
    "rest_framework",
    "corsheaders",
    # my apps
    "misc",
    "todo",
    "org",
    "prod",
    "sales",
    "ae",
    "restut",
    "novelty",          # TODO: delete
    "ponynote",         # TODO: delete
    "timetr",           # TODO: delete
    "tt",               # TODO: delete
]

# INSTALLED_APPS = [
#     # third party apps
#     "simple_history",
# #     "mptt",
#     "webpack_loader", # django-react integration
# ]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # 3rd party middleware
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    # my middleware
    "misc.middleware.RootMiddleware",
]


CORS_ORIGIN_WHITELIST = (
    "localhost:3000/"
)


ROOT_URLCONF = "ffba.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "ffba/templates"),
            os.path.join(BASE_DIR, "sales/templates/sales"),
            os.path.join(BASE_DIR, "prod/templates"),
            os.path.join(BASE_DIR, "ae/templates"),
            os.path.join(BASE_DIR, "ponynote/templates"),
            os.path.join(BASE_DIR, "timetr/templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # my context processors
                "ffba.context.site_settings",
            ],
        },
    },
]


WSGI_APPLICATION = "wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "ru-RU"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_L10N = True

USE_TZ = True

FORMAT_MODULE_PATH = [
    "ffba.formats",
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "ffba/static"),
    os.path.join(BASE_DIR, "timetr/static"),    # TODO: delete
    os.path.join(BASE_DIR, "tt/static"),    # TODO: delete
]

STATIC_ROOT = "/home/ffba/wsp/ffba2/static_root"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_URL = "/logout/"

DATE_FORMAT = "%d.%m.%Y"


REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        # "rest_framework.permissions.IsAdminUser",
        # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    # "PAGE_SIZE": 10
}


# WEBPACK_LOADER = {
#     "DEFAULT": {
#         "BUNDLE_DIR_NAME": "bundles/",
#         "STATS_FILE": os.path.join(BASE_DIR, "webpack-stats.dev.json"),
#     }
# }
